# datafiles to be loaded as objects: mapping
data:
  obj1:
    # settlement data
    settlementFile: settlements1
    # mapping csv > geojson
    settlementProperties:
      URI: settlement_id
      region_URI: region_URI
      top_type: top_type
      names:
        ara_common: names_ara_common
        ara_search: names_ara_search
        ara_translit: names_ara_translit
        ara_common_other: names_ara_common_other
        ara_translit_other: names_ara_translit_other
        eng_common: names_eng_common
        eng_search: names_eng_search
        eng_common_other: names_eng_common_other
        eng_translit_other: names_eng_translit_other
        eng_translit: names_eng_translit
      source: source
      language: languages


    # routes data
    routesFile: routes1
    routesProperties:
      # required fields
      sToponym: sToponym
      eToponym: eToponym
      id: route_id
      Meter: meter
      # additional fields
      terrain: terrain
      safety: safety
      sToponym_type: sToponym_type
      eToponym_type: eToponym_type
    period_start: 800
    period_end: 1000
# additional weight modifiers
modifiers:
  terrain:
    desert: 2
    normal: 1
    mountain: 1.25
    river: 0.75
  safety:
    dangerous: 2
    safe: 0.75
    normal: 1
  sToponym_type:
    metropoles: 4
    capitals: 3
    towns: 2
    villages: 1
    waystations: 1
    sites: 1
    xroads: 1
    waters: 1
    mont: 1
    regions: 1
    quarters: 1
  eToponym_type:
    metropoles: 4
    capitals: 3
    towns: 2
    villages: 1
    waystations: 1
    sites: 1
    xroads: 1
    waters: 1
    mont: 1
    regions: 1
    quarters: 1