# datafiles to be loaded as objects
data:
  obj1:
    settlements: "./Easterland/places_new_structure.geojson"
    routes: "./Easterland/routes.json"
    period_start: 700
    period_end: 1000

# categories
Type:
  Land: 1
  Sea: 1.5
Moai:
  0: 1
  1: 1
  2: 1
  3: 1
  4: 1
  5: 1
  6: 1
  7: 1
  
  

  




